---
  - name: install apache httpd
    apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
    with_items:
      - apache2
      - libapache2-mod-php5
    sudo: yes

  - name: enable mod_rewrite
    apache2_module: name=rewrite state=present
    sudo: yes
    notify:
      - restart apache

  - name: create virtual host
    template: src=omeka.conf.j2 dest=/etc/apache2/sites-available/omeka.conf
    sudo: yes
    notify:
      - restart apache

  - name: enable virtual host
    command: a2ensite omeka
    sudo: yes
    notify:
     - restart apache

  - name: disable default virtual host
    command: a2dissite 000-default
    sudo: yes
    notify:
      - restart apache
