---
  - name: install packages
    apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
    with_items:
      - php5
      - php5-fpm
      - php5-mysql
      - nginx
      - mysql-server
      - python-mysqldb #for ansible
      - unzip
    sudo: yes
