---
  - name: retrieve list of home directories
    command: ls /home
    register: home_dirs

  - name: create data directories
    file: path=/home/{{ item }}/data state=directory
    with_items: home_dirs.stdout_lines

  - name: sync data for users
    synchronize: >
      src=data/
      dest=/home/{{ item }}/data
    with_items: home_dirs.stdout_lines

  - name: set permissions on data directories
    command: >
      chown -R {{ item }}:{{ item }} /home/{{ item }}/data
    with_items: home_dirs.stdout_lines

  - name: create exercises directory
    file: >
      path=/home/{{ item }}/exercises
      owner={{ item }}
      group={{ item }}
      mode=0755
      state=directory
    with_items: home_dirs.stdout_lines

  - name: sync notebooks to home directories
    git: >
      repo=https://github.com/digital-humanities-data-curation/hilt2015.git
      dest=/home/{{ item }}/exercises
      force=yes
    with_items: home_dirs.stdout_lines
    become: yes
    become_user: '{{ item }}'
