---
  - name: download kafka
    get_url: >
      url=http://mirror.cogentco.com/pub/apache/kafka/{{ kafka_version }}/{{ kafka_pkg }}.tgz
      dest=/home/vagrant/{{ kafka_pkg }}.tgz
    sudo: yes

  - name: ensure dir for kafka exists
    file: dest=/usr/local/lib state=directory mode=0755
    sudo: yes

  - name: untar kafka
    unarchive: >
      src=/home/vagrant/{{ kafka_pkg }}.tgz
      dest=/usr/local/lib
      copy=no
    sudo: yes

  - name: symlink kafka
    file: path={{ kafka_workdir }} src=/usr/local/lib/{{ kafka_pkg }} state=link
    sudo: yes

  - name: set advertised hostname in kafka config
    lineinfile: >
      dest="{{ kafka_workdir }}/config/server.properties"
      regexp='#advertised\.host\.name=<hostname routable by clients>'
      line='advertised.host.name={{ private_ip }}'
    sudo: yes
    notify:
      - start kafka

  - name: set advertised port in kafka config
    lineinfile: >
      dest="{{ kafka_workdir }}/config/server.properties"
      regexp='#advertised\.port=<port accessible by clients>'
      line='advertised.port=9092'
    sudo: yes
    notify:
      - start kafka

  - name: uncomment and set hostname in kafka config
    lineinfile: >
      dest="{{ kafka_workdir }}/config/server.properties"
      regexp='#host\.name=localhost'
      line='host.name={{ private_ip }}'
    sudo: yes
    notify:
      - start kafka
