---
  - name: make sure plugins directory exists
    stat: path=/var/www/wordpress/wp-content/plugins
    register: "pth"

  - debug: msg="plugins directory exists"
    when: pth.stat.isdir is defined and pth.stat.isdir

  - name: make sure mu-plugins directory exists
    file: path=/var/www/wordpress/wp-content/mu-plugins state=directory
    sudo: yes

  - name: copy mu-plugin files
    copy: src=kap_functions.php dest=/var/www/wordpress/wp-content/mu-plugins/kap_functions.php
    sudo: yes

  - name: download wp admin ui customize plugin
    get_url: >
      url=https://downloads.wordpress.org/plugin/wp-admin-ui-customize.1.5.6.zip
      dest=/home/vagrant/wp-admin-ui-customize.1.5.6.zip
    sudo: yes

  - name: extract wp-admin-ui
    unarchive: >
      src=/home/vagrant/wp-admin-ui-customize.1.5.6.zip
      dest=/var/www/wordpress/wp-content/plugins/
      copy=no
    sudo: yes

  - name: download wp-rest-api plugin
    get_url: >
      url=https://github.com/WP-API/WP-API/archive/2.0-beta4.tar.gz
      dest=/home/vagrant/wp-api-2.0-beta4.tar.gz
    sudo: yes

  - name: extract wp-rest-api
    unarchive: >
      src=/home/vagrant/wp-api-2.0-beta4.tar.gz
      dest=/var/www/wordpress/wp-content/plugins/
      copy=no
    sudo: yes

  - name: copy child theme files
    copy: src=kap-twenty-fifteen-child.tgz dest=/home/vagrant/kap-twenty-fifteen-child.tgz
    sudo: yes

  - name: make sure theme directory exists
    file: path=/var/www/wordpress/wp-content/themes/kap-twenty-fifteen-child state=directory
    sudo: yes

  - name: load child theme
    unarchive: >
      src=/home/vagrant/kap-twenty-fifteen-child.tgz
      dest=/var/www/wordpress/wp-content/themes/kap-twenty-fifteen-child
      copy=no
    sudo: yes
    notify:
      - restart nginx
