---
  - name: download omeka
    get_url: >
      url=http://omeka.org/files/{{ omeka.pkg }}.zip
      dest=/home/vagrant/{{ omeka.pkg }}.zip
    sudo: yes

  # - name: ensure dir for omeka exists
  #   file: dest=/usr/local/lib state=directory mode=0755
  #   sudo: yes

  - name: unzip omeka
    unarchive: >
      src=/home/vagrant/{{ omeka.pkg }}.zip
      dest=/var/www/
      copy=no
    sudo: yes

  # - name: symlink omeka
  #   file: path=/var/www/{{ omeka.pkg }} src=/usr/local/lib/{{ omeka.pkg }} state=link
  #   sudo: yes

  # - name: remove htaccess
  #   file: path=/var/www/{{ omeka.pkg }}/.htaccess state=absent
  #   sudo: yes

  - name: remove default www
    file: path=/var/www/html state=absent
    sudo: yes

  # - name: put htaccess file
  #   template: src=.htaccess.j2 dest=/var/www/{{ omeka.pkg }}/.htaccess
  #   sudo: yes
  #   notify:
  #     - restart apache

  - name: set file permissions
    file: path=/var/www/{{ omeka.pkg }}/files recurse=yes mode=0777
    sudo: yes

  - name: update db.ini file
    template: src=db.ini.j2 dest=/var/www/{{ omeka.pkg }}/db.ini
    sudo: yes
