---
  - name: download miniconda
    get_url: >
      url=https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
      dest=/root/Miniconda3-latest-Linux-x86_64.sh
      sha256sum="{{ miniconda_sha256sum }}"

  - name: install miniconda
    command: >
      bash /root/Miniconda3-latest-Linux-x86_64.sh -b -p /opt/anaconda
      creates=/opt/anaconda

  - name: install pip
    command: conda install --yes pip
    environment:
      PATH: /opt/anaconda/bin:{{ ansible_env.PATH }}

  - name: create jupyterhub environment
    command: >
      conda create -n {{ conda_env_name }} pip --yes
      creates=/opt/anaconda/envs/hub
    environment:
      PATH: /opt/anaconda/bin:{{ ansible_env.PATH }}

  - name: install dependencies
    command: pip install {{ item }}
    with_items:
      - "ipython[notebook]"
      - sqlalchemy  # for oauthenticator
      - simplepam   # for oauthenticator
      - git+https://github.com/jupyter/oauthenticator.git
    environment:
      PATH: /opt/anaconda/envs/{{ conda_env_name }}/bin:{{ ansible_env.PATH }}

  - name: install additional nice-to-have packages
    command: conda install --name {{ conda_env_name }} {{ item }} --yes
    with_items:
      - seaborn
      - pandas
      - csvkit
    environment:
      PATH: /opt/anaconda/envs/{{ conda_env_name }}/bin:{{ ansible_env.PATH }}

  - name: install jupyterhub
    command: pip install jupyterhub
    environment:
      PATH: /opt/anaconda/envs/{{ conda_env_name }}/bin:{{ ansible_env.PATH }}
