
Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  # config.vm.network :private_network, ip: "192.168.10.31"
  config.vm.network :forwarded_port, guest: 9092, host: 9092
  config.vm.network :forwarded_port, guest: 2181, host: 2181
  config.vm.hostname = "ssmmfm-local"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ssmmfm-kafka"
    vb.memory = "2048"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ssmmfm.yml"
    ansible.inventory_path = "hosts"
    ansible.limit = "ssmmfm-kafka"
    ansible.verbose = 'v'

    ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
  end

end
