
Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.network :private_network, ip: "192.168.33.10"
  config.vm.hostname = "ssmmfm-local"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ssmmfm-kafka"
    vb.memory = "2048"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "kafka.yml"
    ansible.inventory_path = "hosts"
    ansible.limit = "ssmmfm-kafka"
    #ansible.verbose = 'v'

    ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
  end

end
