---
- name: Download Elasticsearch
  get_url: >
    url=https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-{{ es_version }}.tar.gz
    dest=/home/vagrant/elasticsearch-{{ es_version }}.tar.gz
    sha256sum="{{ es_sha256sum }}"

- name: Set elasticsearch to run on boot
  service: name=elasticsearch enabled=yes
  sudo: yes

- name: Set ES_HEAP_SIZE
  lineinfile: >
    dest=/etc/default/elasticsearch
    regexp=^#ES_HEAP_SIZE=2g
    line=ES_HEAP_SIZE=1g
  sudo: yes
  notify: restart elasticsearch

- name: Configure memory locking
  lineinfile: >
    dest=/etc/default/elasticsearch
    regexp=^#MAX_LOCKED_MEMORY=unlimited
    line=MAX_LOCKED_MEMORY=unlimited
  sudo: yes
  notify: restart elasticsearch

- name: Configure systemd for memory locking
  lineinfile: >
    dest=/usr/lib/systemd/system/elasticsearch.service
    regexp=^#LimitMEMLOCK=infinity
    line=LimitMEMLOCK=infinity
  sudo: yes
  notify: restart elasticsearch

- name: Add cluster config
  template: >
    src=elasticsearch.yml.j2
    dest=/etc/elasticsearch/elasticsearch.yml
  notify: start elasticsearch
  sudo: yes
