---
  - name: install mysql
    apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
    with_items:
      - mysql-server
      - python-mysqldb #for ansible
    sudo: yes

  - name: update mysql conf for admins
    template: src=home_my.cnf.j2 dest=/home/ubuntu/.my.cnf
    sudo: yes

  - name: create omeka db
    mysql_db: name={{ db.name }} state=present

  - name: create omeka db user
    mysql_user: name={{ db.user }} password={{ db.password }} priv={{ db.name }}.*:ALL host='{{ db.host }}' state=present
