---
    # Only needed for vagrant b/c synced folders
  - name: Turn off sendfile in nginx.conf
    lineinfile: >
      dest=/etc/nginx/nginx.conf
      regexp='sendfile\son;$'
      line='sendfile off;'
    when: "'vm' in group_names"
    become: yes

  - name: create global nginx conf dir
    file: dest=/etc/nginx/conf/global state=directory
    become: yes

  - name: copy nginx global conf
    copy: src=restrictions.conf dest=/etc/nginx/conf/global/restrictions.conf
    become: yes
    notify: restart nginx

  - name: copy nginx server conf
    template: src=es.j2 dest=/etc/nginx/sites-available/es
    become: yes
    notify: restart nginx

  - name: symlink nginx server conf
    file: src=/etc/nginx/sites-available/es dest=/etc/nginx/sites-enabled/es state=link
    become: yes
    notify: restart nginx

  - name: delete default nginx server conf
    file: path=/etc/nginx/sites-enabled/default state=absent
    become: yes
    notify: restart nginx
