---
  - name: install packages
    apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
    with_items:
      - php5
      - php5-fpm
      - php5-mysql
      - nginx
      - mysql-server
      - python-mysqldb #for ansible
      - unzip
    sudo: yes
    tags:
      - app

  - name: add repository for oracle java
    apt_repository: repo='ppa:webupd8team/java'
    sudo: yes
    tags:
      - search

  - name: accept oracle license
    debconf: >
      name='oracle-java8-installer'
      question='shared/accepted-oracle-license-v1-1'
      value='true'
      vtype='select'
    sudo: yes
    tags:
      - search

  - name: install packages
    apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
    with_items:
      - oracle-java8-installer
    sudo: yes
    tags:
      - search
